# 基础镜像
FROM nginx
# author
MAINTAINER yumi

# 挂载目录
VOLUME /home/yumi/projects/yumi-ui
# 创建目录
RUN mkdir -p /home/yumi/projects/yumi-ui
# 指定路径
WORKDIR /home/yumi/projects/yumi-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/yumi/projects/yumi-ui
