# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER yumi

# 挂载目录
VOLUME /home/yumi
# 创建目录
RUN mkdir -p /home/yumi
# 指定路径
WORKDIR /home/yumi
# 复制jar文件到路径
COPY ./jar/yumi-auth.jar /home/yumi/yumi-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","yumi-auth.jar"]